### ISSUE TITLE
Feature Request: hassio ha password reset

### ISSUE THREAD

**Issue by cogneato** [home-assistant/cli#189]
A command to reset onboarding which would require deleting the files in .storage as described at
<https://www.home-assistant.io/docs/authentication/#lost-owner-password>

**Comment by frenck** [comment]
The hass.io CLI is a client of the Hass.io API, it does not have any capabilities outside of that scope.

Not sure if this request fits here or should be part of this CLI.

**Comment by mjrider** [comment]
the title and description are to different things a password reset and a reset of the whole of homeassistant

**Comment by frenck** [comment]
@mjrider, sure, but in both cases my first response still applies.
