### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by rlpowell** [home-assistant/cli#208]
The README says to install with

    go get -d github.com/home-assistant/cli

, but that doesn't seem to get me anything executable, just a bunch of .go files, and it *definitely* doesn't get me anything called "ha".

If I run it without the -d (and if I have the right compiler and libraries installed), I get /root/go/bin/cli

Am I holding it wrong?

**Comment by frenck** [comment]
That should actually not be used and is still there from the "older" days.

I'll adjust the documentation today.

You can grab the pre-build binaries from here: <https://github.com/home-assistant/cli/releases>

**Comment by frenck** [comment]
I've adjusted the README.
