### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by fabaff** [home-assistant/cli#213]
**Describe the bug**
"2. Output of `ha --version`" is not always available, e.g., after a build with `$ go build -o "ha"`.

**Comment by frenck** [comment]
Feel free to open up an PR to address the issue.

**Comment by fabaff** [comment]
Actually, `ha --version` is not available at all.

![Screenshot-20200325075320-890x676](https://user-images.githubusercontent.com/116184/77509880-d60eb480-6e6d-11ea-8caa-7d785da4cd06.png)
