### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by fabaff** [home-assistant/cli#214]
**Describe the bug**
If the token is invalid the user gets:

```bash
$ export SUPERVISOR_API_TOKEN=wrong_token
$ ./ha os info
ERRO[0000] Unexpected server response                   
Unexpected server response
```

2. Output of `ha --version`
see #213

**Expected behavior**
For me, the error message should tell the user what's wrong (if possible) and not be generic.

**Comment by frenck** [comment]
This information is not provided from upstream.

**Comment by fabaff** [comment]
> The possibility for setting a token is merely used for development and debugging, in the environment where this tool is used, the correct tokens are automatically provided.

Not according to the [README](https://github.com/home-assistant/cli/blob/master/README.md#install). There it's a selling point...

**Comment by frenck** [comment]
Let's adjust the README to make that clear in that case.

**Comment by agners** [comment]
This issue tripped me a bit too, #267 make it print the status code if it is unexpected, which leads to `Unexpected server response. Status code: 403`. This points much more to an authentication issue like a wrong token...
