### ISSUE TITLE
ha addons info command from example does not work

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/cli#217]
**Describe the bug**

Trying to get the CLI to list me information on all addons and it is requiring I provide a slug for a specific addon. When you use `ha addons -h` it lists an example of `ha addons info` as a way to do this but when you actually try to use that command you get an error.  See below:
![Screen Shot 2020-03-26 at 11 49 23 AM](https://user-images.githubusercontent.com/2037026/77667403-83f68d80-6f58-11ea-9afc-f79f7024b807.png)

**Debug info**

1. SSH Addon type:
- [x] Community
- [ ] Core
- [ ] Custom

2. Version of the CLI:
I'm running version 7.3.0 of the SSH & Web Terminal community addon, I'm not sure how to determine what CLI version that uses.

3. Version of Home Assistant Core & the Home Assistant Supervisor
HA Core is 107.6
Supervisor is 209

4. Output from executing the command with debug info.
e.g. `ha hardware info` should be run as `ha -d hardware info`
![Screen Shot 2020-03-26 at 11 59 14 AM](https://user-images.githubusercontent.com/2037026/77667980-3d556300-6f59-11ea-9780-d088fe2b90ab.png)

**Expected behavior**
I expect the command `ha addons info` to return me the list of addons and information on them such as slug, installed version, latest version, etc.

**Additional context**
When you run the command `ha addons` by itself it seems to output the info I would expect to come from `ha addons info`. So this may just be a documentation bug showing a bad example. Although I noticed that the command `ha addons` only seems to work when ssh'ed into HA, if I try to use by passing it in like `ssh <HA Username>@<HA IP> 'ha addons'` I receive a response like this:
```
time="2020-03-26T12:06:01-04:00" level=error msg="Unexpected server response"
Unexpected server response
```
None of the other HA CLI commands seem to run into this issue where they can't be passed into SSH that I tried.

**Comment by frenck** [comment]
`ha addons` shows the list you are looking for.

`ha addons info` should return the information on the current add-on where this command is executed (defaulting to `self`), this is not working indeed and a bug that needs to be addressed.

I'm not sure where you found `-d`, that is not a valid global flag, which is not listed either. `--log-level debug` however, is a valid global flag.

**Comment by mdegat01** [comment]
Ah ok thanks. For the -d thing, When you make a new issue in this repo the issue template tells you to do that.  Or at least that's how I read it, it seemed like the instructions were to run your command with -d so I was just trying to follow them.  Here is the new issue template for reference:

```
**Describe the bug**

A clear and concise description of what the bug is.

**Debug info**

1. SSH Addon type:
- [ ] Community
- [ ] Core
- [ ] Custom

2. Version of the CLI:

3. Version of Home Assistant Core & the Home Assistant Supervisor

4. Output from executing the command with debug info.
e.g. `ha hardware info` should be run as `ha -d hardware info`

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.
e.g. If you are running `ha core check` and the config is known to be broken or good.
```

**Comment by frenck** [comment]
Aah, that is a leftover of the previous (Bash based version). I'll update that issue template as well (man, we keep finding history 😓)
