### ISSUE TITLE
"ha os update" should prompt for confirmation

### ISSUE THREAD

**Issue by rogerjak** [home-assistant/cli#237]
Running HassOS 5.0 beta I typed in "ha os update" in my SSH session.
Then it started to upgrade, no confirmation, no info on to what version and no progress.
Since my installation wouldn't boot after this upgrade, I suspect it downgraded to the latest 4.x version.
That doesn't support RPi4 SSD boot, so I had to clone a new image and restore from snapshot.
The command "ha os update" should at least refuse to downgrade from beta, or prompt with version information if you want to continue.

**Comment by frenck** [comment]
`ha os update` will update to any release that matches the current channel on is on. The update can be an upgrade or downgrade, depending on the matching channel.

The CLI is an admin tool, that does not provide this level of security. If you are in personal need for that level of insurance, please use the UI.

**Comment by rogerjak** [comment]
Personally I don't care, I just think it's good to avoid people from making mistakes.
Sure, it's an admin tool, but so is "apt-get upgrade" and it still prompts me if I want to do the update.
