### ISSUE TITLE
cli root login .114.3 not loading

### ISSUE THREAD

**Issue by anarchking** [home-assistant/cli#252]
Everytime I login. to cli with username root
It starts to load everything but stops at 
(services.d) done
Checked config and no errors, im not sure what im doing wrong

Home Assistant 0.114.3
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.5
hassio | true
host_os | HassOS 3.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.107
python_version | 3.8.3
supervisor | 249
timezone | UTC
version | 0.114.3
virtualenv | false

**Comment by pvizeli** [comment]
You need update OS to 4.x
