### ISSUE TITLE
Feature Request: Interact with Hassio REST API

### ISSUE THREAD

**Issue by wystans** [home-assistant/cli#268]
Is there any interest in expanding the scope of this cli to interact with the [REST API](https://developers.home-assistant.io/docs/api/rest) as well as the Supervisor API? 

This would allow the cli to get state information about devices/entities and call services.

**Comment by frenck** [comment]
This CLI is for controlling the Home Assistant Supervisor, not Home Assistant Core.

If you are looking for a CLI towards the Home Assistant Core API's, there is a third-party one here: <https://github.com/home-assistant-ecosystem/home-assistant-cli>
