### ISSUE TITLE
CLI auth reset fails, does not recognize the internal flag --username

### ISSUE THREAD

**Issue by alfonsolsl** [home-assistant/cli#270]
## The problem
The order: `ha auth reset --username "xxxx" --pasword "xxxxx"`

fails, does not recognize the flag --username but in the internal auth --help shows the exact flag as example. 

## Environment

- Home Assistant Core release with the issue: 2021.1.5
- Last working Home Assistant Core release (if known): -
- Operating environment (OS/Container/Supervised/Core):  VEnv
- Integration causing this issue: -
- Link to integration documentation on our website:  -

## Problem-relevant `configuration.yaml`
 N/A
```yaml

N/a

## Traceback/Error logs


## Additional information
This is a new installation using virtualbox and the official disc image.

**Comment by agners** [comment]
@alfonsolsl I can't reproduce this on my end:

```
ha auth reset --username test --password test
Command completed successfully.
```
Did you maybe use spaces? If so, then this is most likely related to #299

**Comment by alfonsolsl** [comment]
Hello! I did it without any spaces in the username or password, but the error on the Cli is the same of the issue you pointed out.

**Comment by agners** [comment]
I do get errors when using quotes in the current version:

```
ha > auth reset --username "test" --password "test"
Error: Unknown error, see supervisor
```

However, with the changes introduced in https://github.com/home-assistant/plugin-cli/pull/54 this problem seems to be gone as well. So this should be solved with the next CLI/CLI plugin release.
