### ISSUE TITLE
Error returned when using CLi to update Home Assistant

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/cli#292]
## Describe the problem

When I use ha core update --version 2021.x.x ha does update and everything works well however I get an error returned. This has only happened with the latest version of the community SSH & Web Terminal addon.
Issue reported here https://github.com/hassio-addons/addon-ssh/issues/259 but Frenck says it is upstream issue and to report here
## Debug information

1. SSH Addon type

- [ x] Community
- [ ] Core
- [ ] Custom

2. Version of the CLI

CLI Version: 2021.04.1
Add-on: SSH & Web Terminal
Add-on version: 8.2.1

3. Version of Home Assistant Core & the Home Assistant Supervisor

Home Assistant Core: 2021.5.1
Home Assistant Supervisor: 2021.04.3

4. Output from executing the command with debug info

Post "http://supervisor/core/update": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
e.g., `ha hardware info` should be run as `ha --log-level debug hardware info`
```
Post "http://supervisor/core/update": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```

## Expected behavior

I don't expect an error - it never used to error and HA is updated and working. No supervisor errors just that terminal error
## Additional context

e.g., If you are running `ha core check` and the config is known to be broken or good.

**Comment by nenadmilano** [comment]
Any news on this issue? It seems that I cant even restart Home Assistant from the GUI (fortunately just my DEV environment) and I am hesitant to update the PROD system because of this.
