### ISSUE TITLE
'dns': <[uint32 ]> error

### ISSUE THREAD

**Issue by loki-bel** [home-assistant/cli#311]
Hello,
I deployed HassOS 6.4 (VMWare image)  and faced to the same issue like #307 I got error using the following command about DNS settings:

network set enp11s0 --ipv4-nameserver=10.64.21.10
Error: Error parsing parameter 1 of type “a{sa{sv}}”: expected value:
'dns': <[uint32 ]>
                        ^
I tried to use double or simple quotes. Results were the same.
network set enp11s0 --ipv4-nameserver="10.64.21.10"
network set enp11s0 --ipv4-nameserver='10.64.21.10'

I can't use dhcp for some reasons, that's why I need to set up static ip address, gw, dns.

**Comment by agners** [comment]
This problem was caused by the Supervisor itself, see also #3060.

With the latest versions this should no longer be an issue.
