### ISSUE TITLE
Unable to provide a name for cli backup.  backup always assigns it's own slug

### ISSUE THREAD

**Issue by ravenshill** [home-assistant/cli#325]
### The problem

ha backups new --name myname
Processing... Done.

slug: 84d816fb

### What version of Home Assistant Core has the issue?

core-2021.11.5

### What type of installation are you running?

Home Assistant OS

**Comment by ludeeus** [comment]
It looks like you are confusing 2 separate parts.
What you give it is the "name", that does not change the "slug".
All backups are automatically given a "slug", you can not change how that is generated.

The name you set are used by the "name" key when you list backups, and in the UI.
