### ISSUE TITLE
Timeout issues

### ISSUE THREAD

**Issue by thomasmauerer** [home-assistant/cli#332]
I'm developing an addon called Samba Backup and use the CLI tool for creating the backups.
Some users are running into a timeout, since the backup takes more than 3 hours on their systems.

Would it be possible to make the timeout configurable instead of having a hardcoded value?

**Comment by frenck** [comment]
> I'm developing an addon called Samba Backup and use the CLI tool for creating the backups.

I would not recommend on use the CLI for that? Why not directly interface with the API available? <https://developers.home-assistant.io/docs/api/supervisor/endpoints>

**Comment by ludeeus** [comment]
As @frenck mentioned, you should use the API directly from inside your add-on.
If this is still a feature you would like to have added to the CLI, please raise a feature request for it on the forum 👍
