### ISSUE TITLE
Page option (i.e. more, less, etc)

### ISSUE THREAD

**Issue by jangerbauer** [home-assistant/cli#378]
There does not seem to be an option to limit scrolling in the cli.

Example: if I run "ha core logs", I will get multiple lines that I cannot either limit (using less / more).  There also doesn't appear to be an option to scroll back.

One possible caveat is that I am running cli from Virtualbox.  Would appreciate any thoughts / recommendations if I am missing anything.

**Comment by scls19fr** [comment]
I'm also looking for similar feature

**Comment by frenck** [comment]
Combine it with built-in tools like "more" or "less" by piping the output into them? 

I'm not sure why we should built in features that are generally available in Linux?

../Frenck

**Comment by frenck** [comment]
Going to close this request, instead, use the existing Linux tools available.

For example: `ha core log | less`

../Frenck

**Comment by dennis-bell** [comment]
Would like to reopen this, as it does not work.
Yes it works from the addon, but not from the console.

![Image](https://github.com/user-attachments/assets/3c4d9bdc-bd54-41cc-9910-c38c18d1a15d)
