### ISSUE TITLE
Feature Request: report state through CLI for Core Supervisor Dns etc

### ISSUE THREAD

**Issue by mjkl-gh** [home-assistant/cli#414]
I'm working on adding some features to an Ansible implementation that uses the CLI for starting, stopping and updating a Supervised or OS install.

https://github.com/totaldebug/ansible-collection-hassio_cli/pull/9

However, when working on a `--check` functionality which does nothing but check the results of an action I noticed it's possible to stop and start a service, but not get the current status of the service, making it impossible to determine wether a command would change the current state.

Proposed solution:

Add a `state` field to the `info` command of all modules that support `start` or `stop` that reports `running` or `stopped or the like.

If this is something the maintainers are willing to accept I could try to open a PR for this

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
