### ISSUE TITLE
Missing armv7 binary in the latest release

### ISSUE THREAD

**Issue by segabor** [home-assistant/cli#429]
## Describe the problem

See the problem detailed in this ticket https://github.com/home-assistant/plugin-cli/issues/122
It turned out that the `armv7-hassio-cli:2023.09.0` image misses `ha` command grabbed from the latest release.

## Debug information

1. SSH Addon type

- [ ] Community
- [x] Core
- [ ] Custom

2. Version of the CLI

CLI Version: ? (should have been v4.28.0 armv7)
Add-on: ?
Add-on version: ?

3. Version of Home Assistant Core & the Home Assistant Supervisor

Home Assistant Core: 2023.10.0
Home Assistant Supervisor: 2023.10.0

4. Output from executing the command with debug info

e.g., `ha hardware info` should be run as `ha --log-level debug hardware info`
```txt
OCI runtime exec failed: exec failed: unable to start container process: exec /usr/bin/ha: exec format error: unknown
```

## Expected behavior

ha command should be available and do as it shoud normally.

## Additional context

None

**Comment by frenck** [comment]
Fixed in v4.28.1 Sorry!

../Frenck
