### ISSUE TITLE
banner domain name is wrong

### ISSUE THREAD

**Issue by greyltc** [home-assistant/cli#476]
A `.local` domain is hardcoded into the URLs the banner prints:
https://github.com/home-assistant/cli/blob/640d56e9366339724c39fdf4765dd036fbfdfb53/cmd/banner.go#L167-L168

.local is of course not always the correct domain.

I'm not sure what a portable (enough) way is to find the correct domain name is, but in my setup, systemd's `resolvectl` is able to report the correct domain name when you use it like this:
`resolvectl domain | head -n1 | cut -d " " -f 2`
can we assume `resovelctl` is always available?

**Comment by frenck** [comment]
I'm not sure, but a better question is: Why is there a mismatch between the information in the Home Assistant Supervisor vs your system? That sounds like an issue waiting to happen...

**Comment by agners** [comment]
> A `.local` domain is hardcoded into the URLs the banner prints:

Yes, as we rely on mDNS (which uses `.local` as per standard, see [RFC6762](https://datatracker.ietf.org/doc/html/rfc6762)). This is intended to be that way.

What we could debate if we should note the user that he needs to have a mDNS capable system :thinking:  (which, afaik, most OSes are nowadays).
